#!/bin/bash

#Changed '%% ' -> '%%'
#Because of the missing "DMSJRN" rows in output file addressed by Sachin

[[ -z $1 ]] && echo "PRTBIGOBJ output file required as parameter"&& exit 1
INPUT=$1

TMPNAME=/var/tmp/$(basename $0)-$(dd if=/dev/urandom  bs=64 count=1 2>/dev/null | md5sum | awk '{print $1}')

grep '%%' ${INPUT} | awk -F%% '{print $1}' | sed -e 's/,\([0-9]\)/\1/g' -e 's/^ \+//' -e 's/ \+/ /g' | awk '{print $2 "," $3 "," $4 "," $(NF) ","}' > ${TMPNAME}.part1
grep '%%' ${INPUT} | awk -F%% '{print $2}' | sed -e 's/^ \+//' > ${TMPNAME}.part2
paste -d '' ${TMPNAME}.part1 ${TMPNAME}.part2
rm -f ${TMPNAME}.part1 ${TMPNAME}.part2
