#!/bin/bash

#SRVLST="CAM CATS CLUX DFSNZ1 DRSAP2PF GDC GVA HKGA HNL INDO ITL KOREA KSENV5U KSENV6 KSENV6U LAX1 MIDEAST MIDPAC PAD1 PAX1 PRC SFO SFO2 SIN2 SYD"
SRVLST="SFO"

for SRV in ${SRVLST}
do
    for BKP in SAVDLY SAVMSB SAVWSB
    do
        echo "Extracting data for ${BKP} on ${SRV}"
        DATFILE=./out/${SRV}_${BKP}.out
        ssh OPSSON@${SRV}.dfs "system 'PRTRPTBRM TYPE(*CTLGRPSTAT) CTLGRP('${BKP}')'" | grep ${BKP} > ${DATFILE}

        [[ ! -f ${DATFILE} ]] && echo "Failed to extract ${BKP} data on ${SRV}. No output. Skipping" | tee -a failed && continue
        [[ $(ls -l ${DATFILE} | awk '{print $5}') == 0 ]] && echo "Failed to extract ${BKP} data on ${SRV}. Zero output. Skipping" | tee -a failed && continue
    
        while read LN
        do
            read CTRLGRP DT_START TM_START DT_END TM_END DURATION SAVED NSAVED SIZE RATE MEDIA VOL STATUS <<< ${LN} 

            TS_START=$(/home/shared/bin/as400_dt_convert --from ${SRV} -d "${DT_START} ${TM_START}" --format "+%s" 2>/dev/null)
            TS_END=$(/home/shared/bin/as400_dt_convert --from ${SRV} -d "${DT_END} ${TM_END}" --format "+%s" 2>/dev/null)
            
            if [[ -z ${STATUS} ]] 
            then
                STATUS=${MEDIA}
                MEDIA=''
                VOL=''
            fi

            [[ ${STATUS} == '*ACT' ]] && echo "Skipping active ${BKP} on ${SRV}" && continue

            echo "INSERT INTO BACKUPS \
                VALUES('${SRV}', '${CTRLGRP}', ${TS_START}, ${TS_END}, ${SAVED}, ${NSAVED}, ${SIZE}, ${RATE}, '${MEDIA}', '${VOL}', '${STATUS}');" |\
                    sqlite3 ../as400_stats
            if [[ $? != 0 ]]
            then
                echo "INSERT INTO BACKUPS \
                    VALUES('${SRV}', '${CTRLGRP}', ${TS_START}, ${TS_END}, ${SAVED}, ${NSAVED}, ${SIZE}, ${RATE}, '${MEDIA}', '${VOL}', '${STATUS}');" | tee -a failed
            fi
            
            unset CTRLGRP DT_START TM_START DT_END TM_END DURATION SAVED NSAVED SIZE RATE MEDIA VOL STATUS
        done < ${DATFILE}

    done
done
