#!/bin/bash

PREFIX=$(dirname $0)
DB=${PREFIX}/../data/as400/as400_stats

BKPTYPE="SAVDLY SAVMSB SAVWSB"
LIMIT=2
SRVLST="CAM CATS CLUX DFSNZ1 DRSAP2PF FRANCE GDC GVA HKGA HNL INDO ITL KOREA KSENV5U KSENV6 KSENV6U LAX1 MIDEAST MIDPAC PAD1 PAX1 PRC SFO SFO2 SIN2 SYD"

while [[ -n $1 ]]
do
    case $1 in
        --filter|-f)
            shift
            SRVLST=$1
            ;;
        --limit|-l)
            shift
            LIMIT=$1
            ;;
        --type|-t)
            shift
            BKPTYPE=$1
            ;;
        *)
            echo "Invalid option $1" && exit 1
            ;;
    esac
    shift
done

echo 'Server,Type,Status,"Start Date (SGT)","Start Time (SGT)","End Date (SGT)","End Time (SGT)","Start Date (System)","Start Time (System)","End Date (System)","End Time (System)","Duration","Duration (Sec)","Obj. Saved","Obj. Unsaved",Size,Volume'
for SRV in ${SRVLST}
do
    TZ=$(echo "SELECT tz FROM SERVERS WHERE host = '${SRV}';" | sqlite3 ${DB})
    for LN in $(echo "SELECT start, end, obj_saved, obj_nsaved, save_size, status, ctrlgrp, volume FROM BACKUPS\
        WHERE host = '${SRV}' ORDER BY start DESC LIMIT ${LIMIT};" | sqlite3 ${DB})
    do
        read START END SAVED NSAVED SIZE STATUS CTRLGRP VOL <<< $(echo ${LN} | sed -e 's/|/ /g')
        STARTSGT=$(TZ='Asia/Singapore' date -d "@${START}" '+%d/%m/%y %H:%M')
        ENDSGT=$(TZ='Asia/Singapore' date -d "@${END}" '+%d/%m/%y %H:%M')
        STARTSYS=$(TZ=${TZ} date -d "@${START}" '+%d/%m/%y %H:%M')
        ENDSYS=$(TZ=${TZ} date -d "@${END}" '+%d/%m/%y %H:%M')
        DURATION1=$((${END} - ${START}))
        DURATION2=$(printf '%d:%02d:%02d\n' $((${DURATION1}/3600)) $(((${DURATION1}%3600)/60)) $(((${DURATION1}%3600)%60)))
        case ${STATUS} in
            \*NOERR|\*QUAL) STATUS='OK' ;;
            *) STATUS='KO' ;;
        esac

        PROCEED=1
        for TYPE in ${BKPTYPE}
        do
            [[ ${CTRLGRP} == ${TYPE} ]] && PROCEED=0 && break
        done

        [[ ${PROCEED} == 1 ]] && continue

        case ${CTRLGRP} in
            SAVDLY) TYPE='Incremental' ;;
            SAVMSB) TYPE='Full (Monthly)' ;;
            SAVWSB) TYPE='Full (Weekly)' ;;
            *) echo "Bug: Unknown backup type ${CTRLGRP}" && exit 1
        esac

        [[ -z ${VOL} ]]  && VOL='N/A'

        echo "${SRV},${TYPE},${STATUS},\"$(echo ${STARTSGT} | awk '{print $1}')\",\"$(echo ${STARTSGT} | awk '{print $2}')\",\"$(echo ${ENDSGT} | awk '{print $1}')\",\"$(echo ${ENDSGT} | awk '{print $2}')\",\"$(echo ${STARTSYS} | awk '{print $1}')\",\"$(echo ${STARTSYS} | awk '{print $2}')\",\"$(echo ${ENDSYS} | awk '{print $1}')\",\"$(echo ${ENDSYS} | awk '{print $2}')\",${DURATION2},${DURATION1},${SAVED},${NSAVED},${SIZE},${VOL}"
    done
done
